global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
      
  - job_name: 'sample-apps'
    static_configs:
      - targets: ['python-app:5000', 'nodejs-app:3000', 'java-app:8080']
